# Tekhnologicheskaya praktika
## Rabota s Numpy

Дан массив, содержащий баллы слушателей курса по английскому языку за вступительный экзамен. Слушатели распределены по 15 группам по 10 человек.

In [1]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

### Задание 1

Посчитать, сколько слушателей получили 0 за вступительный экзамен.

In [22]:
col = len(list(filter(lambda x: True if x == 0 else False, scores.min(axis=1).ravel())))
print(col)

9


### Задание 2

Посчитать, сколько слушателей получили балл выше 50.

In [28]:
col = len(list(filter(lambda x: True if x > 50 else False, scores.flat)))
print(col)

64


### Задание 3

Посчитать, сколько человек получили балл не ниже 50, но не выше 70.

In [30]:
col = len(list(filter(lambda x: True if x >= 50 and x <= 70 else False, scores.flat)))
print(col)

26


### Задание 4

Определить, в какой группе средний балл за вступительный экзамен выше.

In [45]:
np.where(np.mean(scores, axis=1) == np.mean(scores, axis=1).max())

(array([9]),)

### Задание 5

Сохранить баллы слушателей выше 0 в массив `nonzero`. 

In [52]:
nonzero = scores[np.where(scores != 0)]
print(nonzero)

[ 20  40  56  80   5  25  27  74   1  98  67 100   8  56  34  82 100   7
  78  54  23  79 100  42  95  83  51  50  47  23 100  94  25  48  38  77
  90  87  41  89  52   5  17  28  99  32  18  21  18  29  31  48  62  76
  22   6  65  78  43  22  38  88  94 100  77  28  39  41  81  45  54  98
  12  66  88  44  55 100  12  11  17  70  86  96  56  23  32  49  70  80
  20  24  76  50  29  40   3   2   5  11  33  63  28  40  51 100  98  87
  22  30  16  54  78  12  25  35  10  19  67 100  88  24  33  47  56  62
  34  77  53  50  89  70  72  56  29  15  20]


### Задание 6

Используя массив `nonzero`, определить минимальный балл за вступительный балл среди всех групп.

In [53]:
min_bal = nonzero.min() 

### Задание 7

Выбрать из массива `nonzero` только те значения, которые соответствуют продвинутому уровню знания языка – баллу за экзамен выше 80. Сохранить полученный результат в массив `advanced`. 

In [58]:
advanced = nonzero[np.where(nonzero > 80)]

### Задание 8

Получить из исходного массива `scores` массив медианных оценок по группам.

In [55]:
np.mean(scores, axis=1)

array([32.8, 55.2, 55.4, 55.3, 50.8, 35.7, 53.4, 47.5, 37.6, 57.9, 26. ,
       55.2, 31.6, 57.4, 40.1])

### Задание 9

Перераспределить студентов из `scores` в 10 групп по 15 человек с помощью метода `reshape`. Посчитать среднюю оценку в группе на обновленных данных.

In [56]:
scores.reshape(10, 15)

array([[ 20,  40,  56,  80,   0,   5,  25,  27,  74,   1,   0,  98,  67,
        100,   8],
       [ 56,  34,  82, 100,   7,  78,  54,  23,  79, 100,   0,   0,  42,
         95,  83],
       [ 51,  50,  47,  23, 100,  94,  25,  48,  38,  77,  90,  87,  41,
         89,  52],
       [  0,   5,  17,  28,  99,  32,  18,  21,  18,  29,  31,  48,  62,
         76,  22],
       [  6,   0,  65,  78,  43,  22,  38,  88,  94, 100,  77,  28,  39,
         41,   0],
       [ 81,  45,  54,  98,  12,  66,   0,  88,   0,  44,   0,  55, 100,
         12,  11],
       [ 17,  70,  86,  96,  56,  23,  32,  49,  70,  80,  20,  24,  76,
         50,  29],
       [ 40,   3,   2,   5,  11,  33,  63,  28,  40,  51, 100,  98,  87,
         22,  30],
       [ 16,  54,  78,  12,  25,  35,  10,  19,  67,   0, 100,  88,  24,
         33,  47],
       [ 56,  62,  34,  77,  53,  50,  89,  70,  72,  56,  29,  15,  20,
          0,   0]])

### Задание 10

Определить общее число элементов в массиве `advanced`.

In [59]:
len(advanced)

28

### Задание 11

На основе исходного массива `scores` создать булев массив `sto`, где `True` соответствует баллам за экзамен, равным 100, а `False` – всем остальным баллам. 

In [60]:
sto = scores == 100

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

### Задание 12

На основе исходного массива `scores` вывести на экран оценки слушателей первых семи групп (включительно, должны быть 7 списков оценок).

In [61]:
scores[:7,]

array([[ 20,  40,  56,  80,   0,   5,  25,  27,  74,   1],
       [  0,  98,  67, 100,   8,  56,  34,  82, 100,   7],
       [ 78,  54,  23,  79, 100,   0,   0,  42,  95,  83],
       [ 51,  50,  47,  23, 100,  94,  25,  48,  38,  77],
       [ 90,  87,  41,  89,  52,   0,   5,  17,  28,  99],
       [ 32,  18,  21,  18,  29,  31,  48,  62,  76,  22],
       [  6,   0,  65,  78,  43,  22,  38,  88,  94, 100]])

In [1]:
from scipy.stats import mannwhitneyu

In [ ]:
from random import rand